[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "rm -rf .next && bun install && bun run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_FORCE_CACHE_CLEAR = "true"
  NETLIFY_NEXT_PLUGIN_LOGGING = "verbose"

[[plugins]]
  package = "@netlify/plugin-nextjs"
